
export const ActionTypes={
    SET_RECIPES : "SET_RECIPES",
    SELECTED_RECIPE : "SELECTED_RECIPE",
    REMOVE_SELECTED_RECIPE : "REMOVE_SELECTED_RECIPE",
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGOUT_REQUEST : "LOGOUT_REQUEST",
    SUCCESS : "SUCCESS",
    FAILURE : "FAILURE"
};