server:
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/recipe_app
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql : true
  http:
    encoding:
      charset : UTF-8
      enabled: true
      force:  true
      force-request: true
      force-response: true
  security:
    basic:
      enabled: false
hibernate:
  validator:
    apply_to_ddl: false
    autoregister_listeners: false